env:
  global:
    - ANDROID_PACKAGE='ngdemo-debug.apk'
    - ANDROID_PACKAGE_FOLDER=$TRAVIS_BUILD_DIR/platforms/android/build/outputs/apk
    - ANDROID_SAUCE_STORAGE="https://saucelabs.com/rest/v1/storage/$SAUCE_USER/$ANDROID_PACKAGE?overwrite=true"
    - IOS_PACKAGE='ngdemo.zip'
    - IOS_PACKAGE_FOLDER=$TRAVIS_BUILD_DIR/platforms/ios/build/emulator
    - IOS_SAUCE_STORAGE="https://saucelabs.com/rest/v1/storage/$SAUCE_USER/$IOS_PACKAGE?overwrite=true"

matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "6"
      script: npm i && npm run tslint
    - stage: "WebPack"
      os: osx
      env:
        - Webpack="iOS"
      osx_image: xcode8.3
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      before_install: pod repo update && npm run clean
      script: npm run build-ios-bundle
    - language: android
      os: linux
      env:
        - Webpack="Android"
      jdk: oraclejdk8
      before_install: nvm install 6.10.3 && npm run clean
      script: npm run build-android-bundle
    - stage: "Build"
      env:
        - BuildAndroid="25"
      language: android
      os: linux
      jdk: oraclejdk8
      before_install: nvm install 6.10.3 && npm run clean
      script:
        - tns build android
        - "curl -u $SAUCE_USER:$SAUCE_KEY -X POST -H 'Content-Type: application/octet-stream' $ANDROID_SAUCE_STORAGE --data-binary @$ANDROID_PACKAGE_FOLDER/$ANDROID_PACKAGE"
    - os: osx
      env:
        - BuildiOS="10.3"
        - Xcode="8.3"
      osx_image: xcode8.3
      language: node_js
      node_js: "6"
      jdk: oraclejdk8
      before_install: pod repo update && npm run clean
      script:
        - tns build ios
        - cd $IOS_PACKAGE_FOLDER && zip -r $IOS_PACKAGE demo.app
        - "curl -u $SAUCE_USER:$SAUCE_KEY -X POST -H 'Content-Type: application/octet-stream' $IOS_SAUCE_STORAGE --data-binary @$IOS_PACKAGE_FOLDER/$IOS_PACKAGE"
    - stage: "UI Tests"
      env:
      - Android="23"
      language: node_js
      os: linux
      node_js: "6"
      before_install: npm i
      script:
        - npm i -g appium
        - npm run appium --runType=android23 --sauceLab=true --appLocation=$ANDROID_PACKAGE
    - os: linux
      env:
        - iOS="10"
      language: node_js
      node_js: "6"
      before_install: npm i
      script:
        - npm i -g appium
        - npm run appium --runType=ios-simulator103iPhone6 --sauceLab=true --appLocation=$IOS_PACKAGE

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository

before_cache:
    - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
    directories:
        - .nvm
        - $HOME/.gradle/caches/
        - $HOME/.gradle/wrapper/

install:
    - npm install -g nativescript
    - tns usage-reporting disable
    - tns error-reporting disable
